#!/bin/bash

python /home/amli/TGMamba/train.py \
    --save_dir "/home/amli/TGMamba/results/template" \
    --rand_seed 547 \
    --dataset 'tuhz' \
    --dataset_has_fft \
    --seq_pool_type max \
    --vertex_pool_type max \
    --conv_type graphconv \
    --model_dim 32 \
    --state_expansion_factor 16 \
    --local_conv_width 4 \
    --num_tgmamba_layers 1 \
    --rmsnorm \
    --edge_learner_layers 3 \
    --edge_learner_time_varying \
    --edge_learner_attention \
    --attn_softmax_temp 0.01 \
    --attn_threshold 0.15 \
    --init_skip_param 0.175 \
    --train_batch_size 256 \
    --val_batch_size 256 \
    --test_batch_size 256 \
    --num_workers 12 \
    --lr_init 0.00035 \
    --weight_decay 0.231 \
    --optimizer_name adamw \
    --scheduler cosine \
    --num_epochs 200 \
    --patience 50 \
    --gpu_id 3 \